[[gdstk]]
arch = "aarch64"
git-tree-sha1 = "5cfe09a4b5f56e16984ef22d5614027e9d9c5834"
os = "macos"

    [[gdstk.download]]
    sha256 = "065ba4ec18b9a8834615b45887e23ee8707a548e8cebc45287b3a58fd2bb0ed4"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.57+0/gdstk.v0.9.57.aarch64-apple-darwin.tar.gz"
[[gdstk]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b89f7770c3b4b238714388d55364577126856d7"
libc = "glibc"
os = "linux"

    [[gdstk.download]]
    sha256 = "17ec2299eb8e4d119c4db7a399dc434a1353f27c46e38697e0a58f0e62fed0e1"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.57+0/gdstk.v0.9.57.aarch64-linux-gnu-cxx11.tar.gz"
[[gdstk]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48eaa27cce5a060124005d43063d83c0a44e4a1f"
libc = "musl"
os = "linux"

    [[gdstk.download]]
    sha256 = "76e2e453c9b0c5a7d5b6eb9a541d675bb9d90812f05e3dd4dce2f74dedd4dc6c"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.57+0/gdstk.v0.9.57.aarch64-linux-musl-cxx11.tar.gz"
[[gdstk]]
arch = "aarch64"
git-tree-sha1 = "6cbfb0a52932a4cc7c8d800c9bb7239dcb35dc64"
os = "freebsd"

    [[gdstk.download]]
    sha256 = "a7c88981b82051a0551e6ab1b07dc353ba09e3b44b66fb0b0ad575bdc6e047c7"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.57+0/gdstk.v0.9.57.aarch64-unknown-freebsd.tar.gz"
[[gdstk]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1573c9df1831d37c63cc0d7ed8aad1f0484a73a5"
libc = "glibc"
os = "linux"

    [[gdstk.download]]
    sha256 = "206588c7bb8e8d2cffbfa638c985fdf3d1d5cc92f8327c3655a116eb2d68e3ec"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.57+0/gdstk.v0.9.57.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gdstk]]
arch = "x86_64"
git-tree-sha1 = "20df8628973b960d0b4a0d5134d9efb1ac8176e4"
os = "macos"

    [[gdstk.download]]
    sha256 = "68f9a4fd5a82a86b6d937d607774c71220fd94561258860851e2c47bf5a90656"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.57+0/gdstk.v0.9.57.x86_64-apple-darwin.tar.gz"
[[gdstk]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ff9dee3e686ebc07e186a521bdce79bd2d26175"
libc = "glibc"
os = "linux"

    [[gdstk.download]]
    sha256 = "b20a096615f611af74eeb9d5046dd375473b4397eccabc9bf8bebe9cb258ee40"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.57+0/gdstk.v0.9.57.x86_64-linux-gnu-cxx11.tar.gz"
[[gdstk]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9375074299b9439750382e40b7a7a26ac2ba86c8"
libc = "musl"
os = "linux"

    [[gdstk.download]]
    sha256 = "d48037b5de0953d46765851c0106ff92e06e082eb934a6a25f875987edfa535b"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.57+0/gdstk.v0.9.57.x86_64-linux-musl-cxx11.tar.gz"
[[gdstk]]
arch = "x86_64"
git-tree-sha1 = "8ccaf4accae2a424145412b8ce57b82ce3afc5a6"
os = "freebsd"

    [[gdstk.download]]
    sha256 = "1687675cd68a5975c9c034da6bfa5c318db0fa2ce307caa56498987d36c14bac"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.57+0/gdstk.v0.9.57.x86_64-unknown-freebsd.tar.gz"
[[gdstk]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe0fb26484d553648bde3ce45fe8be6228824c48"
os = "windows"

    [[gdstk.download]]
    sha256 = "8071b1fece1be57f46aae0ab96115f6d8cb84d204752e74b485f0ad46be24bc9"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.57+0/gdstk.v0.9.57.x86_64-w64-mingw32-cxx11.tar.gz"
[[gdstk]]
arch = "aarch64"
git-tree-sha1 = "04418a53b2d41f699c4adf684e0bd51c9af17fee"
julia_version = "1.11.1"
os = "macos"

    [[gdstk.download]]
    sha256 = "0cebe11846bdffa0d4420f6f2b9d4886a83fbcb375976a9a312173d43e6b93b1"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.59+0/gdstk.v0.9.59.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a0b5e69de617ee11335e03d0c6cb49fe8c3a3f5"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[gdstk.download]]
    sha256 = "400de2ed73f0bffc3b93d316ae4f9f730b6bfc52590ed20d1452adb8d9bacf5c"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.59+0/gdstk.v0.9.59.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6097ef28642ca45cc0e2047195e17a583f2446c0"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[gdstk.download]]
    sha256 = "4e78378ce62a263ad47a5aaa81ec1edd9a836fc6e869868eeb7f7329cf94470a"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.59+0/gdstk.v0.9.59.aarch64-linux-musl-cxx11-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36670aa91a0d82026e4c21b142746221a0c9132d"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[gdstk.download]]
    sha256 = "6203d74868a3b35c7c810cd3809676e531409b23541dc497e19de8782b78cc0b"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.59+0/gdstk.v0.9.59.powerpc64le-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "x86_64"
git-tree-sha1 = "7749f7f1dddb6dd6c58def2024c993de11355b0b"
julia_version = "1.11.1"
os = "macos"

    [[gdstk.download]]
    sha256 = "f203dd29b847dd609fef4933ffd7149f5bdda7b39da25cfe0a141932f0e10ab7"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.59+0/gdstk.v0.9.59.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf1a9a02c627e4265d4aff5d7515ae22e8e7a97d"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[gdstk.download]]
    sha256 = "6562a9b38a549707b9e4a5f228a62de1b86977cec7085431706dd85ffed37a22"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.59+0/gdstk.v0.9.59.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07aeeb9fc6acc4d4546c6c1c951192b3f353ec7c"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[gdstk.download]]
    sha256 = "8c8cdad19776d34f1b49b3810ebe0bfe743bbf48b96c3fa751702dc52d40e264"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.59+0/gdstk.v0.9.59.x86_64-linux-musl-cxx11-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f2da376885ea253c12d0560f576b59e23a36659"
julia_version = "1.11.1"
os = "windows"

    [[gdstk.download]]
    sha256 = "25d4b74222ec165dde053b00ff67df64429f46904746957f0de5e23b291675f7"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.59+0/gdstk.v0.9.59.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "aarch64"
git-tree-sha1 = "9bf307dd27f2829560aadb2a89a7a4e0995b6f6e"
julia_version = "1.11.1"
os = "macos"

    [[gdstk.download]]
    sha256 = "37e4b5f80a24abdb2d6ae7642ea6ff544caed41bda263b8d9bbf9b1f1f528b3b"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.60+0/gdstk.v0.9.60.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e409690540871e94271489cebe6f7435faef091"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[gdstk.download]]
    sha256 = "04bf622f80ce6a08c41ff13940ef3d1576da50e2a2e9d59860cdfd409b7f7daf"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.60+0/gdstk.v0.9.60.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18b2cf02644c8cc78f9027a9072c5bcb28c6f617"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[gdstk.download]]
    sha256 = "975860f0b9eaec3a022c14431e689d82f81c21aec27b20f46c01d79e737e97d0"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.60+0/gdstk.v0.9.60.aarch64-linux-musl-cxx11-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b6f42cfe1652e43b0bf93cc32e7254a3ae7fa6a"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[gdstk.download]]
    sha256 = "5522fbbb1c66c8e1bdb8166aff794c773891cf49b9adabde26b6db693aca980e"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.60+0/gdstk.v0.9.60.powerpc64le-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "x86_64"
git-tree-sha1 = "ef4fda923a126da32da3637c4ca6112dd01edf47"
julia_version = "1.11.1"
os = "macos"

    [[gdstk.download]]
    sha256 = "88d887d0d69d70a224e28c06330d755d655db5ab891ae1864047c2dbd0abb890"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.60+0/gdstk.v0.9.60.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "786c31d98b8b60f132f2af13281960fd39b5eee5"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[gdstk.download]]
    sha256 = "76255322518daa39a1354b0f6bbf05b7b20b100cf1d2147b360a53ac20c1f11b"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.60+0/gdstk.v0.9.60.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ca3665f5733e0de716f6fa57739f15bbddf5d45"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[gdstk.download]]
    sha256 = "576083398281ddbbd6db5ba39a58a36d6db14a0adc0413bfb7f5738071c11f83"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.60+0/gdstk.v0.9.60.x86_64-linux-musl-cxx11-julia_version+1.11.1.tar.gz"
[[gdstk]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d5fdc70076520fb88c58b9a5dd243055e684708"
julia_version = "1.11.1"
os = "windows"

    [[gdstk.download]]
    sha256 = "0238fe9fb91eccbfda46c9610cc1a1e841749c44f72138e42a86657805d3e7b7"
    url = "https://github.com/MadebyDaris/GdstkWrapper_jll.jl/releases/download/gdstk-v0.9.60+0/gdstk.v0.9.60.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
