# Autogenerated wrapper script for gdstk_jll for x86_64-w64-mingw32-cxx11-julia_version+1.11.1
export libgdstk, libgdstk_wrapper

using Zlib_jll
using Qhull_jll
using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("gdstk")
JLLWrappers.@declare_library_product(libgdstk, "libgdstk.dll")
JLLWrappers.@declare_library_product(libgdstk_wrapper, "libgdstk_wrapper.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, Qhull_jll, libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libgdstk,
        "bin\\libgdstk.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libgdstk_wrapper,
        "bin\\libgdstk_wrapper.dll",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
