# Autogenerated wrapper script for gdstk_jll for x86_64-linux-musl-cxx11
export libgdstk, libgdstk_wrapper

using Zlib_jll
using Qhull_jll
using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("gdstk")
JLLWrappers.@declare_library_product(libgdstk, "libgdstk.so")
JLLWrappers.@declare_library_product(libgdstk_wrapper, "libgdstk_wrapper.so")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, Qhull_jll, libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libgdstk,
        "lib/libgdstk.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libgdstk_wrapper,
        "lib/libgdstk_wrapper.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
