# Autogenerated wrapper script for gdstk_jll for x86_64-apple-darwin-julia_version+1.11.1
export libgdstk, libgdstk_wrapper

using Zlib_jll
using Qhull_jll
using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("gdstk")
JLLWrappers.@declare_library_product(libgdstk, "@rpath/libgdstk.dylib")
JLLWrappers.@declare_library_product(libgdstk_wrapper, "@rpath/libgdstk_wrapper.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, Qhull_jll, libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libgdstk,
        "lib/libgdstk.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libgdstk_wrapper,
        "lib/libgdstk_wrapper.dylib",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
